### PR TITLE
Database setup

### PR DESCRIPTION
**Pull request by Aliin**
I think for now my database setup is fine, so I'd have you look at the code and then merge it onto master so you can use the database :)

### CODE REVIEW

**Comment by Mortiferr** [comment]
That's a lot of commits :open_mouth:

**Comment by Aliin** [comment]
Put a lot of work into it :D

**Comment by olgierd-on-fire** [comment]
So far so good. setup_db() function is big. We can split it later.

**Comment by olgierd-on-fire** [comment]
@Aliin  I'm coding to split setup_db() function. But what is more important between code that works or clean code right now? We make sure this I think.

**Comment by olgierd-on-fire** [comment]
I have fixed two. Check my commit in my local Symposium, Display-Posts branch and two commits. It's not important but this is related above question.

**Comment by Aliin** [comment]
Code needs to be well organized, make sense, be understandable and well commented and so on. We don't have to get picky if there are some slight formal errors like wrong indentation spacing or something like that. It's good to learn how to right nice code but the aesthetics aren't the top priority. It should be clear what the code does, the code should not be ambiguous, and must work. Otherwise I think the priority is on getting stuff done and helping each other out with not working code and problems in the code.

**Comment by Aliin** [comment]
I just looked at your changes they're fine. You can usually just commit to this repository directly, if there's any change that makes problems we can always undo the change if we decide so.

**Comment by Aliin** [comment]
Oh there is one problem. Can you please apply the changes not to the Display-Posts branch but to the Database-Setup branch? That is important. The Database-Setup branch is the one we want all changes concerning the database setup on.
Then we copy the changes to the display-posts and submit-posts branches.

**Comment by Aliin** [comment]
forks  This is how the forks work right now.

**Comment by Aliin** [comment]
If you say it's ready I'll merge it into master.

**Comment by olgierd-on-fire** [comment]
@Aliin I will say it's ready to merge. But i think not yet. I'm gonna find to clean more.

**Comment by olgierd-on-fire** [comment]
@Aliin If you are doing with submit-posts branch, then you may need to pull latest php files from Database-Setup. Because I did push some things to keep psr in directly.

**Comment by olgierd-on-fire** [comment]
@Aliin It's ready to merge into master.

**Pull request merged**
